<<<<<<< HEAD
Traceback (most recent call last):
  File "/home/ubuntu/trading_broker/download_market_data.py", line 25, in <module>
    df_existing = pd.read_csv(file_path)
NameError: name 'pd' is not defined. Did you mean: 'id'?
=======
Updated data saved to /home/ubuntu/trading_broker/market_data/NIFTY_1m.csv
Updated data saved to /home/ubuntu/trading_broker/market_data/NIFTY_5m.csv
Updated data saved to /home/ubuntu/trading_broker/market_data/NIFTYBANK_1m.csv
Updated data saved to /home/ubuntu/trading_broker/market_data/NIFTYBANK_5m.csv
Updated data saved to /home/ubuntu/trading_broker/market_data/RELIANCE_1m.csv
Updated data saved to /home/ubuntu/trading_broker/market_data/RELIANCE_5m.csv
>>>>>>> 72bf180225d1c95fd15d109efcb4f58de9afa63c
